import React from 'react'
import Header from './Header'
import LeftAside from './LeftAside'
import Section from './Section'
import RightAside from './RightAside'
import Footer from './Footer'

export default function comanLayout({children}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container a_tbdr p-0">
        <Header />
        <main className="a_tbdr m-3 row">
            <LeftAside />
            { children }
            <RightAside />
        </main>
        <Footer />
      </div>
    </div>
  )
}
